### ISSUE TITLE
Feedback on current update.. bug: calendar doesn't update for notes from other (non visible) months.

### ISSUE THREAD

**Issue by ksdavidc** [bartkessels/daily-note-calendar#72]
Okay. I am sorry this should probably be divided into separate issues, but I wanted to give some feedback on the current update.

## First the bug:
- bug: if I am on a different month's note, the calendar doesn't seem to update. The two panes are not synchronized in that case, but ARE in the case of current month.

## Ideas:
- I think it might be cool if i am on a date's daily note (via some other means, e.g. switching tabs), calendar could reflect that I am on that date. Right now it only shows that if I click on that day in the calendar. In other words, I don't mean necessarily showing that day's notes, or actually moving the calendar to that date. Just reflecting the day that corresponds to the currently shown daily note.
- This would not be as necessary for non daily notes, perhaps, but it might be interesting.
- This is far out, and possibly something for a separate plugin, but the code would be similar. Right now the calendar is based on the created date. What about a calendar based on the **modification** date?

## GUI improvements
- I think the GUI should distinguish several things: 
    - current day, 
    - if in a dn is being viewed in a tab, that date should be somehow highlighted if in the visible month.
    - currently selected date (showing notes for that date and potentially opening that day's daily note) (since this would overlap with the above, these two should be mutually compatible but separate)
    - days that have notes (but no daily notes). I think there should be a separate indicator for days that have notes...is that what you said you were still working on?
    - date being hovered

- For example, currently I am using the css snippet below to make the panel look like this: 

<img width="463" alt="image" src="https://github.com/user-attachments/assets/b2eaeaf2-c718-4af1-afb1-a833a77bc77c" />

- Some of it is a matter of taste, but notice it uses border/background to show currently selected date, and the greyish "blip"(after: border) to show days that have daily notes). It also chooses a better color/brightness filter for the hover (see the 8th) as in my theme this is so faint, I didn't even realize it was happening.
- note that the 9th has notes, but no daily note. The 2nd as well, but that is not clear. I think there should be a way to indicate this in the calendar.
- the current day is bolder and brighter, but in a color similar to other days for consistency. I aim to strike a balance between being distinct but not being distracting, since the current day is not a central function.
- I would ideally bring the little heart calendar and nav buttons down a hair to line up with the title, but haven't gone that far. Clicking the calendar goes to the right month, but doesn't indicate the day...alas.
- I like that you distinguish the quarterly note as Q1, but the periodic (week in month) values have a duplicated first value which I don't understand. I am guessing it is related to periodic notes, which I am not using, so I am not sure what they are intended for. At least, I think they should be distinguished further.

- For comparison

<img width="466" alt="image" src="https://github.com/user-attachments/assets/a5d88994-afe0-454c-911f-6c0bbf9aa527" />

```css

/* fix hover */
.dnc td:hover:not(:empty), .dnc th:hover:not(:empty) {
  /*   background-color: var(--background-modifier-active-hover); *//* original */
    background-color: var(--text-accent); /* this color works better in my theme */
     filter: brightness(150%); /* makes it brighter */
    border-radius: 10%; /* match has note */
}

/* fix title of calendar */
.dnc .header  {
        background: var(--text-accent);
        margin: auto;
}
.dnc .header h1 {
    font-weight: var(--font-bold);
   color: hsl(var(--foreground));
}
.dnc .header span.title {
    margin: auto; /* centers the title */
}

/* adds border to calendar */
.dnc table  {
  border-bottom: 2px solid var(--text-accent);
}

/* border for selected day */
.dnc .selected-day {
    border: 1px solid red; /* red is easy to see , in case text-accent not defined */
    border-radius: 10%; /* adds curve for aesthetic reasons */
    background: var(--text-accent);
}

/* removes notification at bottom, replaced with border at .dnc .selected-day  */
.dnc .selected-day:after {
    border-bottom: none; /* removes this. */
}


/* this is just for has notes */
.dnc .has-note:after { 
border-bottom: 0.3em solid var(--text-faint); /* makes wider, a bit more visible */
border-radius: 10%; /* adds curve for aesthetic reasons */
}


/* current day is bolder and brighter, but keeps color */
.dnc #today {
font-weight: bold; /* bolder */
color: var(--text-faint); /* color is closer to other days */
opacity: 100%; /* brighter */
}

/* this day notes list indent */
 .dnc ul {
  margin: 10px;
}   
```

**Comment by ksdavidc** [comment]
Improved the css a bit more. Makes the hover less intrusive, and improves the navigation buttons.
<img width="528" alt="image" src="https://github.com/user-attachments/assets/cc7a4d0e-1eb6-4916-bfb7-8ac14f512c3e" />

```css
 

/* fix hover */
.dnc td , .dnc th {
        border: 1px solid transparent; /* prevents size change */
}
.dnc td:hover:not(:empty), .dnc th:hover:not(:empty) {
  /*   background-color: var(--background-modifier-active-hover); *//* original */
  /*  background-color: var(--text-accent); *//* removed this. this color works better in my theme */
     filter: brightness(115%); /* makes it brighter */
    border-radius: 13px; /* match has note */
        border: 1px solid var(--text-faint); /* was using red, but now this color matches the other text **/
}
.dnc td.selected-day:hover:not(:empty), .dnc th.selected-day:hover:not(:empty) {
background-color: var(--text-accent); /* preserves background on hover */
}

/* fix title of calendar */
.dnc .header  {
        background: var(--text-accent);
        margin: auto;
        border-radius: 4px;
}
.dnc .header h1 {
    font-weight: var(--font-bold);
   color: hsl(var(--foreground));
}
.dnc .header span.title {
    margin: auto; /* centers the title */
}

/* adds border to calendar */
.dnc table  {
  border-bottom: 2px solid var(--text-accent);
}

/* border for selected day */
.dnc .selected-day {
    border-radius: 13px; /* adds curve for aesthetic reasons */
    background: var(--text-accent);
}

/* removes notification at bottom, replaced with border at .dnc .selected-day  */
.dnc .selected-day:after {
    border-bottom: none; /* removes this. */
}


/* this is just for has notes */
.dnc .has-note:after { 
border-bottom: 0.3em solid var(--text-faint); /* makes wider, a bit more visible */
border-radius: 13px; /* I like this curve a little better */
}


/* current day is bolder and brighter, but keeps color */
.dnc #today {
font-weight: bold; /* bolder */
color: var(--text-faint); /* color is closer to other days */
opacity: 100%; /* brighter */
}

/* this day notes list indent */
 .dnc ul {
  margin: 10px;
}   

/* I think this works a little better, as I hate text overflow. a bit hacky, but no easy way to change font size responsively */
.dnc thead tr th {
overflow-x: clip;
}

/* fix buttons disappearing */
.dnc .header .buttons {
    padding-top:6px; /* adjust position to line up better with title hacky since I don't know where the mismatch is coming from */
    margin-right: 3px;
}
.dnc .header .buttons > *:hover {
    background: var(--text-faint); /* make it stand out */
    border-radius: 3px; /* nicer */
}

```
